source 'https://rubygems.org'

gem 'praxis', git: 'https://github.com/rightscale/praxis.git', branch: "master"
gem 'rack', '~> 1.0'
gem 'rake'
gem 'thin'

# TODO:~ comment out for production
# gem 'pry'
# gem 'pry-byebug'

group :development, :test do
  gem 'rspec'
end
