source 'https://rubygems.org'

gem 'praxis', git: 'git@github.com:rightscale/praxis.git', branch: "master"
gem 'rack', '~> 1.0'
gem 'rake'
gem 'pry'
gem 'pry-byebug'

group :development, :test do
  gem 'rspec'
end
