source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'multi_json'
gem 'yajl-ruby'
gem 'pry'
gem "rainbows", ">=4.6.1"
gem "rack-mount"
gem "eventmachine"

gem 'praxis'
gem 'aws-sdk-core', require: 'seahorse'
gem 'activesupport', require: 'active_support/inflector'

group :test do
  gem 'vcr'
  gem 'rack-test', require: 'rack/test'
  gem 'webmock', '~>1.15.0'
  gem 'rspec', '~> 2.10'
end
